---
abstract: 'A Perl module to deal with time periods.'
author:
  - 'Patrick Ryan, Paul Boyd <boyd.paul@gmail.com>'
build_requires:
  POSIX: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Time-Period
requires:
  Exporter: '0'
  perl: '5.001'
version: '1.25'
